name: uts
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  # (Opsional) kalau mau tegasin versi Flutter:
  # flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
